### ISSUE TITLE
Add jQuery select example

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-conc-examples#2]
Based on https://select2.org/data-sources/ajax the example vue-multiselect can be ported to jQuery as well.

**Comment by stefandesu** [comment]
We could fairly easily use that to create an example using a scheme that is available in a normal JSKOS API (either jskos-server or DANTE). But since requesting data from a Skosmos instance is more complicated, it would be better to use cocoda-sdk. I didn't see an option in Select2 that would make it easy to use custom async requests though.
